package com.test.cust_wih;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomWIH implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CustomWIH() {
    }




}